language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false

